GameServerManagers/Game-Server-Configs

- 7DaysToDie/serverconfig.xml
Also was missing close tag for ServerSettings
> Property fix for A15

- CallOfDuty4/server.cfg
As we spoke there https://github.com/callofduty4x/CoD4x_Server/issues/103
> Cod4x config

- NuclearDawn/server.cfg
- TeamFortress2/mapcycle.txt
- TeamFortress2/motd.txt
- TeamFortress2/server.cfg
I noticed Nuclear Dawn was missing and that the TF2 config was a bit lean, so I added and rewrote some that I used to use for competitive servers.
> Adding Nuclear Dawn and updating TF2

- Arma3/server.cfg
For more info check out here: https://community.bistudio.com/wiki/Arma_3_Analytics
Enabled by default as that's what Bohemia ships the game with, ~~might want to disable to save on bandwidth!~~
> Add server analytics option to Arma 3 config

- UnrealTournament99/Default.ini
Removed a few master servers and added missing packages
Full master server list - Maybe a wiki page?
```
ServerActors=IpServer.UdpServerUplink MasterServerAddress=utmaster.epicgames.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.333networks.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.errorist.tk MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.newbiesplayground.net MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.oldunreal.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master2.oldunreal.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink …
```
> Removed master servers, added missing packages

- TheSpecialists/server.cfg
I'm implementing support for The Specialists Half Life mod and would like to have it's defaults server.cfg added to the Collection so fn_fetch_default_config can fetch it
> added default config for The Specialists

- IOSoccer/server.cfg
related for adding the gameserver to lgsm
> add config for IOSoccer

- ReturnToCastleWolfenstein/server.cfg
adding server config for feature/rtcwserver
> initial rtcwserver server.cfg

- 7DaysToDie/serverconfig.xml
Update configuration file for version A17
> Update configuration for A17

- Dystopia/server.cfg
preparing add dystopia to lgsm
based on dystopia linux server guide
https://github.com/dysemjay/dys-server-guide
> Dystopia config

- NuclearDawn/server.cfg
it seems the config file for ND have been added to a branch years ago, but forgotten since. i'd like to push it to master branch to investigate the possibility of supporting this game
> re-add Nuclear Dawn config file

- SoldierOfFortune2Gold/mapcycle.txt
- SoldierOfFortune2Gold/server.cfg
Addition of the Soldier Of Fortune 2: Gold Edition configuration files for feature/sof2gold. The configuration file is a good baseline but there are a few minor things I will eventually update in it nothing prohibiting from day 1 working.
> Soldier Of Fortune 2: Gold Edition configuration files

- MedalOfHonorAlliedAssault/server.cfg
Im looking into add this game to LGSM, so i need to upload config file to the config repo in order to do full test
> Add Medal of Honor Allied Assault config file

- CounterStrikeGlobalOffensive/server.cfg
Official description for the `sv_lan` command:
> Server is a lan server ( no heartbeat, no authentication, no non-class C addresses )
> Add more info to the sv_lan command

- SoldierOfFortune2Gold/server.cfg
Minor update to fix "./sof2server details" artifacts and correct sv_hostname
> updated syntax

- Waterfall/config.yml
adding Waterfall config for future implementation of waterfall in LGSM
> Waterfall config

- PavlovVR/Game.ini
add deault config
reference:
GameServerManagers/LinuxGSM#2382
> feat(pvrserver): add new configs for Pavlov VR

- JediKnightIIJediOutcast/server.cfg
first step to properly support a new game
> add Jedi Outcast config file

- Eco/Network.eco
#https://github.com/GameServerManagers/LinuxGSM/issues/2271
> Add missing Network.eco

- ActionHalfLife/server.cfg
the last unfulfilled HL mod
https://github.com/GameServerManagers/LinuxGSM/issues/623
> Add Action Half-Life config file

- Insurgency/server.cfg
> Fix typo in sv_vote_kick_troll_min_ratio

- Insurgency/server.cfg
> Remove sv_nwi_banlist from Insurgency config

- DayOfInfamy/server.cfg
DOI config file is just a pile of mess, so i decided to rewrite to more readable format
> Rewrite DOI config file

- Battalion1944/DefaultGame.ini
If this gets merged, does it affect new installs and updates of LinuxGSM bt1944 servers? I'm not familiar with the LinuxGSM codebase.
> Update default config for Battalion 1944

- DayOfInfamy/server.cfg
Add a default playlist so the server wont stuck in default map and giving server owner the possibility to testing their server
> Update DOI config file

- MinecraftBedrock/server.properties
That's the default config shipped with the server archive from https://www.minecraft.net/en-us/download/server/bedrock/
Required for https://github.com/GameServerManagers/LinuxGSM/pull/2566
> Added config for Minecraft Bedrock

- MinecraftBedrock/server.properties
New settings:
- compression-threshold
- server-authoritative-movement
- player-movement-score-threshold
- player-movement-distance-threshold
- player-movement-duration-threshold-in-ms
- correct-player-movement
> Updated config for Minecraft Bedrock v1.13.3.0

- PavlovVR/Game.ini
The missing bracket proably is here the problem.
Tested after i manually added it to the config and the config was not wiped in this case.
> fix Pavlov VR config

- ColonySurvival/colserver.json
https://github.com/GameServerManagers/LinuxGSM/pull/3075
> feat: inital config for Colony Survival

- ColonySurvival/colserver.json
https://github.com/GameServerManagers/LinuxGSM/pull/3075
> fix: update config to new format

- SCPSecretLaboratory/config_gameplay.txt
- SCPSecretLaboratory/config_localadmin.txt
Add configs for SCP: Secret Laboratory and SCP: Secret Laboratory ServerMod
https://github.com/GameServerManagers/LinuxGSM/issues/1995
Connected to:
https://github.com/GameServerManagers/LinuxGSM/pull/3163
> feat: scp secret labratory configs

- DayOfDragons/Game.ini
Adds the initial config for Day of Dragons for
https://github.com/GameServerManagers/LinuxGSM/issues/2572
> feat: add Day of Dragons config

- DayOfInfamy/cvars/full_cvar_list.txt
- DayOfInfamy/server.cfg
- Insurgency/cvars/full_cvar_list.txt
Insurgency and Day of Infamy:
New cvar lists have been generated using the latest game versions.
Day of Infamy: updated cvars in server.cfg
Fixes #94
> Update INS/DoI full cvar lists and fix invalid cvars in DoI server config

- TeamFortress2/cvars/full_cvar_list.txt
Matches the one from April 28, 2020 available at https://developer.valvesoftware.com/wiki/List_of_TF2_console_commands_and_variables.
> Update Team Fortress 2 full_cvar_list.txt to version 5830736

- DayZ/server.cfg
Added DayZ config based on official documentation with follow Arma 3 config style.
https://community.bistudio.com/wiki/DayZ:Server_Configuration#Main_Parameters
> feat: add DayZ config

- Battalion1944/DefaultGame.ini
Update with free to play edition config file
> Update BATTALION: Legacy config file

- ArmaReforger/server.json
Nothing special. Changed order of variables to follow new example in official documentation.
https://community.bistudio.com/wiki/Arma_Reforger:Server_Hosting
> fix(armar): change order of variables

- jk3/server.cfg
Added a jk3 server config to be able to use with https://github.com/GameServerManagers/LinuxGSM/pull/3891
Similar settings to jk2 but a few differences
> feat: add jk3server config
